name: "release to itch.io"
on: push

env:
  GODOT_VERSION: 4.6.1
  EXPORT_NAME: ttt
  PROJECT_PATH: .
  ITCH_USERNAME: trzeh
  ITCH_GAME_ID: ttt

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web

  deploy-to-itch:
    name: Deploy to Itch.io
    runs-on: ubuntu-latest
    needs: [export-web] 
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: builds

      - name: Setup Butler
        uses: remarkablegames/setup-butler@v2

      - name: Push to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: butler push builds/web ${{ env.ITCH_USERNAME }}/${{ env.ITCH_GAME_ID }}:html --userversion 0.0.1-${GITHUB_SHA::7}
